// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudm_UEAU

UDM UE Authentication Service.
© 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.4

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package ueauthentication

import (
	"github.com/gin-gonic/gin"
	"github.com/omec-project/udm/logger"
)

// Post /:supi/hss-security-information/:hssAuthType/generate-av
// Generate authentication data for the UE in EPS or IMS domain
func HTTPGenerateAv(c *gin.Context) {
	detail := "Handle Post /:supi/hss-security-information/:hssAuthType/generate-av is not implemented"
	logger.UeauLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}
