// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudm_UEAU

UDM UE Authentication Service.
© 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.4

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package ueauthentication

import (
	"github.com/gin-gonic/gin"
	"github.com/omec-project/udm/logger"
)

// Get /:supiOrSuci/security-information-rg
// Get authentication data for the FN-RG
func HTTPGetRgAuthData(c *gin.Context) {
	detail := "Handle Get /:supiOrSuci/security-information-rg is not implemented"
	logger.UeauLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}
