// Copyright (c) 2026 Intel Corporation
// Copyright 2019 free5GC.org
// SPDX-License-Identifier: Apache-2.0

/*
Nudm_UEAU

UDM UE Authentication Service.
© 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.4

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package ueauthentication

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/openapi/v2"
	"github.com/omec-project/openapi/v2/models"
	"github.com/omec-project/openapi/v2/utils"
	"github.com/omec-project/udm/logger"
	"github.com/omec-project/udm/producer"
	"github.com/omec-project/util/httpwrapper"
)

// Post /:supi/auth-events
// Create a new confirmation event
func HTTPConfirmAuth(c *gin.Context) {
	logger.UeauLog.Infoln("Handle Post /:supi/auth-events")
	var authEvent models.AuthEvent
	// step 1: retrieve http request body
	requestBody, err := c.GetRawData()
	if err != nil {
		problemDetail := utils.ProblemDetailsSystemFailure(err.Error())
		logger.UeauLog.Errorf("Get Request Body error: %+v", err)
		c.JSON(http.StatusInternalServerError, problemDetail)
		return
	}

	// step 2: convert requestBody to openapi models
	err = openapi.Decode(&authEvent, requestBody, contentTypeJson)
	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := utils.ProblemDetailsMalformedRequestSyntax(problemDetail)
		logger.UeauLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
		return
	}

	req := httpwrapper.NewRequest(c.Request, authEvent)
	req.Params["supi"] = c.Params.ByName("supi")

	rsp := producer.HandleConfirmAuthDataRequest(req)
	writeResponse(c, rsp)
}

func writeResponse(c *gin.Context, rsp *httpwrapper.Response) {
	for key, val := range rsp.Header { // header response is optional
		if len(val) > 0 {
			c.Header(key, val[0])
		}
	}
	if rsp.Body == nil {
		c.Status(rsp.Status)
		return
	}

	responseBody, err := openapi.SetBody(rsp.Body, contentTypeJson)
	if err != nil {
		logger.UeauLog.Errorln(err)
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(rsp.Status, contentTypeJson, responseBody.Bytes())
	}
}
