// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudm_UECM

Nudm Context Management Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package uecontextmanagement

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/udm/logger"
)

// Post /:ueId/registrations/send-routing-info-sm
// Retrieve addressing information for SMS delivery
func HTTPSendRoutingInfoSm(c *gin.Context) {
	logger.UecmLog.Warnln("Handle Post /:ueId/registrations/send-routing-info-sm is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}
