// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudm_UECM

Nudm Context Management Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package uecontextmanagement

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/udm/logger"
)

// Get /:ueId/registrations/smsf-non-3gpp-access
// retrieve the SMSF registration for non-3GPP access information
func HTTPGetNon3GppSmsfRegistration(c *gin.Context) {
	logger.UecmLog.Warnln("Handle Get /:ueId/registrations/smsf-non-3gpp-access is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}
