// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudm_UECM

Nudm Context Management Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package uecontextmanagement

import (
	"github.com/gin-gonic/gin"
	"github.com/omec-project/udm/logger"
)

// Delete /:ueId/registrations/nwdaf-registrations/:nwdafRegistrationId
// delete an NWDAF registration
func HTTPNwdafDeregistration(c *gin.Context) {
	detail := "Handle Delete /:ueId/registrations/nwdaf-registrations/:nwdafRegistrationId is not implemented"
	logger.UecmLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}
