// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudm_UECM

Nudm Context Management Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package uecontextmanagement

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/openapi/v2/models"
	"github.com/omec-project/udm/logger"
	utilLogger "github.com/omec-project/util/logger"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name string
	// Method is the string for the HTTP method (e.g., GET, POST, etc.)
	Method string
	// Pattern is the pattern of the URI.
	Pattern string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

type routeParamAlias struct {
	canonical string
	original  string
}

// NewRouter returns a new router.
func NewRouter() *gin.Engine {
	router := utilLogger.NewGinWithZap(logger.GinLog)
	AddService(router)
	return router
}

// AddService adds routes to an existing gin engine.
func AddService(engine *gin.Engine) *gin.RouterGroup {
	group := engine.Group("/nudm-uecm/v1")
	for _, route := range getRoutes() {
		if shouldSkipRoute(route.Pattern) {
			continue
		}
		if route.HandlerFunc == nil {
			route.HandlerFunc = DefaultHandleFunc
		}
		ginPattern, aliases := canonicalizeRoutePattern(route.Pattern)
		handlerFunc := wrapRouteHandler(route.HandlerFunc, aliases)
		switch route.Method {
		case http.MethodGet:
			group.GET(ginPattern, handlerFunc)
		case http.MethodOptions:
			group.OPTIONS(ginPattern, handlerFunc)
		case http.MethodPost:
			group.POST(ginPattern, handlerFunc)
		case http.MethodPut:
			group.PUT(ginPattern, handlerFunc)
		case http.MethodPatch:
			group.PATCH(ginPattern, handlerFunc)
		case http.MethodDelete:
			group.DELETE(ginPattern, handlerFunc)
		}
	}

	return group
}

// Default handler for not yet implemented routes
func DefaultHandleFunc(c *gin.Context) {
	writeNotImplementedProblem(c, "This API route is not implemented")
}

func writeNotImplementedProblem(c *gin.Context, detail string) {
	problemDetails := models.NewProblemDetails()
	problemDetails.SetStatus(http.StatusNotImplemented)
	problemDetails.SetCause("NOT_IMPLEMENTED")
	problemDetails.SetDetail(detail)
	c.JSON(http.StatusNotImplemented, problemDetails)
}

func shouldSkipRoute(pattern string) bool {
	return strings.Contains(pattern, "request.body#")
}

func canonicalizeRoutePattern(pattern string) (string, []routeParamAlias) {
	segments := strings.Split(pattern, "/")
	aliases := make([]routeParamAlias, 0)
	for index, segment := range segments {
		if len(segment) <= 1 || segment[0] != ':' {
			continue
		}
		original := segment[1:]
		canonical := fmt.Sprintf("param%d", index)
		segments[index] = ":" + canonical
		if original != canonical {
			aliases = append(aliases, routeParamAlias{canonical: canonical, original: original})
		}
	}
	return strings.Join(segments, "/"), aliases
}

func wrapRouteHandler(handler gin.HandlerFunc, aliases []routeParamAlias) gin.HandlerFunc {
	if len(aliases) == 0 {
		return handler
	}

	return func(c *gin.Context) {
		for _, alias := range aliases {
			value := c.Param(alias.canonical)
			if value == "" {
				continue
			}
			c.Params = append(c.Params, gin.Param{Key: alias.original, Value: value})
		}
		handler(c)
	}
}

func getRoutes() []Route {
	return []Route{
		{
			"Get3GppRegistration",
			http.MethodGet,
			"/:ueId/registrations/amf-3gpp-access",
			HTTPGet3GppRegistration,
		},
		{
			"GetNon3GppRegistration",
			http.MethodGet,
			"/:ueId/registrations/amf-non-3gpp-access",
			HTTPGetNon3GppRegistration,
		},
		{
			"Call3GppRegistration",
			http.MethodPut,
			"/:ueId/registrations/amf-3gpp-access",
			HTTPCall3GppRegistration,
		},
		{
			"Non3GppRegistration",
			http.MethodPut,
			"/:ueId/registrations/amf-non-3gpp-access",
			HTTPNon3GppRegistration,
		},
		{
			"IpSmGwDeregistration",
			http.MethodDelete,
			"/:ueId/registrations/ip-sm-gw",
			HTTPIpSmGwDeregistration,
		},
		{
			"IpSmGwRegistration",
			http.MethodPut,
			"/:ueId/registrations/ip-sm-gw",
			HTTPIpSmGwRegistration,
		},
		{
			"GetIpSmGwRegistration",
			http.MethodGet,
			"/:ueId/registrations/ip-sm-gw",
			HTTPGetIpSmGwRegistration,
		},
		{
			"NwdafDeregistration",
			http.MethodDelete,
			"/:ueId/registrations/nwdaf-registrations/:nwdafRegistrationId",
			HTTPNwdafDeregistration,
		},
		{
			"NwdafRegistration",
			http.MethodPut,
			"/:ueId/registrations/nwdaf-registrations/:nwdafRegistrationId",
			HTTPNwdafRegistration,
		},
		{
			"GetNwdafRegistration",
			http.MethodGet,
			"/:ueId/registrations/nwdaf-registrations",
			HTTPGetNwdafRegistration,
		},
		{
			"PeiUpdate",
			http.MethodPost,
			"/:ueId/registrations/amf-3gpp-access/pei-update",
			HTTPPeiUpdate,
		},
		{
			"Update3GppRegistration",
			http.MethodPatch,
			"/:ueId/registrations/amf-3gpp-access",
			HTTPUpdate3GppRegistration,
		},
		{
			"UpdateNon3GppRegistration",
			http.MethodPatch,
			"/:ueId/registrations/amf-non-3gpp-access",
			HTTPUpdateNon3GppRegistration,
		},
		{
			"UpdateNwdafRegistration",
			http.MethodPatch,
			"/:ueId/registrations/nwdaf-registrations/:nwdafRegistrationId",
			HTTPUpdateNwdafRegistration,
		},
		{
			"UpdateSmfRegistration",
			http.MethodPatch,
			"/:ueId/registrations/smf-registrations/:pduSessionId",
			HTTPUpdateSmfRegistration,
		},
		{
			"UpdateSmsf3GppRegistration",
			http.MethodPatch,
			"/:ueId/registrations/smsf-3gpp-access",
			HTTPUpdateSmsf3GppRegistration,
		},
		{
			"UpdateSmsfNon3GppRegistration",
			http.MethodPatch,
			"/:ueId/registrations/smsf-non-3gpp-access",
			HTTPUpdateSmsfNon3GppRegistration,
		},
		{
			"RetrieveSmfRegistration",
			http.MethodGet,
			"/:ueId/registrations/smf-registrations/:pduSessionId",
			HTTPRetrieveSmfRegistration,
		},
		{
			"UpdateRoamingInformation",
			http.MethodPost,
			"/:ueId/registrations/amf-3gpp-access/roaming-info-update",
			HTTPUpdateRoamingInformation,
		},
		{
			"SmfDeregistration",
			http.MethodDelete,
			"/:ueId/registrations/smf-registrations/:pduSessionId",
			HTTPSmfDeregistration,
		},
		{
			"GetSmfRegistration",
			http.MethodGet,
			"/:ueId/registrations/smf-registrations",
			HTTPGetSmfRegistration,
		},
		{
			"Registration",
			http.MethodPut,
			"/:ueId/registrations/smf-registrations/:pduSessionId",
			HTTPRegistration,
		},
		{
			"Get3GppSmsfRegistration",
			http.MethodGet,
			"/:ueId/registrations/smsf-3gpp-access",
			HTTPGet3GppSmsfRegistration,
		},
		{
			"Call3GppSmsfDeregistration",
			http.MethodDelete,
			"/:ueId/registrations/smsf-3gpp-access",
			HTTPCall3GppSmsfDeregistration,
		},
		{
			"Non3GppSmsfDeregistration",
			http.MethodDelete,
			"/:ueId/registrations/smsf-non-3gpp-access",
			HTTPNon3GppSmsfDeregistration,
		},
		{
			"GetNon3GppSmsfRegistration",
			http.MethodGet,
			"/:ueId/registrations/smsf-non-3gpp-access",
			HTTPGetNon3GppSmsfRegistration,
		},
		{
			"Call3GppSmsfRegistration",
			http.MethodPut,
			"/:ueId/registrations/smsf-3gpp-access",
			HTTPCall3GppSmsfRegistration,
		},
		{
			"Non3GppSmsfRegistration",
			http.MethodPut,
			"/:ueId/registrations/smsf-non-3gpp-access",
			HTTPNon3GppSmsfRegistration,
		},
		{
			"SendRoutingInfoSm",
			http.MethodPost,
			"/:ueId/registrations/send-routing-info-sm",
			HTTPSendRoutingInfoSm,
		},
		{
			"DeregAMF",
			http.MethodPost,
			"/:ueId/registrations/amf-3gpp-access/dereg-amf",
			HTTPDeregAMF,
		},
		{
			"TriggerPCSCFRestoration",
			http.MethodPost,
			"/restore-pcscf",
			HTTPTriggerPCSCFRestoration,
		},
		{
			"AuthTrigger",
			http.MethodGet,
			"/:ueId/registrations/auth-trigger",
			HTTPAuthTrigger,
		},
		{
			"GetRegistrations",
			http.MethodGet,
			"/:ueId/registrations",
			HTTPGetRegistrations,
		},
		{
			"GetLocationInfo",
			http.MethodGet,
			"/:ueId/registrations/location",
			HTTPGetLocationInfo,
		},
		{
			"DataRestorationNotificationAmf3gppRequestBodyDataRestorationCallbackUriPost",
			http.MethodPost,
			"/:request.body#/dataRestorationCallbackUri",
			HTTPDataRestorationNotificationAmf3gppRequestBodyDataRestorationCallbackUriPost,
		},
		{
			"DeregistrationNotificationAmf3gppRequestBodyDeregCallbackUriPost",
			http.MethodPost,
			"/:request.body#/deregCallbackUri",
			HTTPDeregistrationNotificationAmf3gppRequestBodyDeregCallbackUriPost,
		},
		{
			"PcscfRestorationNotificationAmf3gppRequestBodyPcscfRestorationCallbackUriPost",
			http.MethodPost,
			"/:request.body#/pcscfRestorationCallbackUri",
			HTTPPcscfRestorationNotificationAmf3gppRequestBodyPcscfRestorationCallbackUriPost,
		},
		{
			"ReauthNotificationRequestBodyReauthNotifyCallbackUriPost",
			http.MethodPost,
			"/:request.body#/reauthNotifyCallbackUri",
			HTTPReauthNotificationRequestBodyReauthNotifyCallbackUriPost,
		},
		{
			"DataRestorationNotificationAmfNon3gppRequestBodyDataRestorationCallbackUriPost",
			http.MethodPost,
			"/:request.body#/dataRestorationCallbackUri",
			HTTPDataRestorationNotificationAmfNon3gppRequestBodyDataRestorationCallbackUriPost,
		},
		{
			"DeregistrationNotificationAmfNon3gppRequestBodyDeregCallbackUriPost",
			http.MethodPost,
			"/:request.body#/deregCallbackUri",
			HTTPDeregistrationNotificationAmfNon3gppRequestBodyDeregCallbackUriPost,
		},
		{
			"PcscfRestorationNotificationAmfNon3gppRequestBodyPcscfRestorationCallbackUriPost",
			http.MethodPost,
			"/:request.body#/pcscfRestorationCallbackUri",
			HTTPPcscfRestorationNotificationAmfNon3gppRequestBodyPcscfRestorationCallbackUriPost,
		},
		{
			"ReauthNotificationAmfNon3gppRequestBodyReauthNotifyCallbackUriPost",
			http.MethodPost,
			"/:request.body#/reauthNotifyCallbackUri",
			HTTPReauthNotificationAmfNon3gppRequestBodyReauthNotifyCallbackUriPost,
		},
		{
			"DataRestorationNotificationRequestBodyDataRestorationCallbackUriPost",
			http.MethodPost,
			"/:request.body#/dataRestorationCallbackUri",
			HTTPDataRestorationNotificationRequestBodyDataRestorationCallbackUriPost,
		},
		{
			"DeregistrationNotificationRequestBodyDeregCallbackUriPost",
			http.MethodPost,
			"/:request.body#/deregCallbackUri",
			HTTPDeregistrationNotificationRequestBodyDeregCallbackUriPost,
		},
		{
			"PcscfRestorationNotificationRequestBodyPcscfRestorationCallbackUriPost",
			http.MethodPost,
			"/:request.body#/pcscfRestorationCallbackUri",
			HTTPPcscfRestorationNotificationRequestBodyPcscfRestorationCallbackUriPost,
		},
		{
			"StaleCheckNotificationRequestBodyStaleCheckCallbackUriPost",
			http.MethodPost,
			"/:request.body#/staleCheckCallbackUri",
			HTTPStaleCheckNotificationRequestBodyStaleCheckCallbackUriPost,
		},
		{
			"DataRestorationNotificationSmsf3gppRequestBodyDataRestorationCallbackUriPost",
			http.MethodPost,
			"/:request.body#/dataRestorationCallbackUri",
			HTTPDataRestorationNotificationSmsf3gppRequestBodyDataRestorationCallbackUriPost,
		},
		{
			"DataRestorationNotificationSmsfNon3gppRequestBodyDataRestorationCallbackUriPost",
			http.MethodPost,
			"/:request.body#/dataRestorationCallbackUri",
			HTTPDataRestorationNotificationSmsfNon3gppRequestBodyDataRestorationCallbackUriPost,
		},
	}
}
