// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudm_SDM

Nudm Subscriber Data Management Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package subscriberdatamanagement

import (
	"github.com/gin-gonic/gin"
	"github.com/omec-project/udm/logger"
)

// Get /:supi/5mbs-data
// retrieve a UE's 5MBS Subscription Data
func HTTPGetMbsData(c *gin.Context) {
	detail := "Handle Get /:supi/5mbs-data is not implemented"
	logger.SdmLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}
