// Copyright (c) 2026 Intel Corporation
// Copyright 2019 free5GC.org
// SPDX-License-Identifier: Apache-2.0

/*
Nudm_SDM

Nudm Subscriber Data Management Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package subscriberdatamanagement

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/openapi/v2"
	"github.com/omec-project/openapi/v2/models"
	"github.com/omec-project/openapi/v2/utils"
	"github.com/omec-project/udm/logger"
	"github.com/omec-project/udm/producer"
	"github.com/omec-project/util/httpwrapper"
)

// Post /:ueId/sdm-subscriptions
// subscribe to notifications
func HTTPSubscribe(c *gin.Context) {
	logger.SdmLog.Infoln("Handle Post /:ueId/sdm-subscriptions")
	var sdmSubscriptionReq models.SdmSubscription

	// step 1: retrieve http request body
	requestBody, err := c.GetRawData()
	if err != nil {
		problemDetail := utils.ProblemDetailsSystemFailure(err.Error())
		logger.SdmLog.Errorf("Get Request Body error: %+v", err)
		c.JSON(http.StatusInternalServerError, problemDetail)
		return
	}

	// step 2: convert requestBody to openapi models
	err = openapi.Decode(&sdmSubscriptionReq, requestBody, contentTypeJson)
	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := utils.ProblemDetailsMalformedRequestSyntax(problemDetail)
		logger.SdmLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
		return
	}

	req := httpwrapper.NewRequest(c.Request, sdmSubscriptionReq)
	req.Params["ueId"] = c.Params.ByName("ueId")

	rsp := producer.HandleSubscribeRequest(req)

	for key, val := range rsp.Header { // header response is optional
		if len(val) > 0 {
			c.Header(key, val[0])
		}
	}
	responseBody, err := openapi.SetBody(rsp.Body, contentTypeJson)
	if err != nil {
		logger.SdmLog.Errorln(err)
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(rsp.Status, contentTypeJson, responseBody.Bytes())
	}
}
