// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudm_SDM

Nudm Subscriber Data Management Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package subscriberdatamanagement

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/udm/logger"
)

// Get /:supi/v2x-data
// retrieve a UE's V2X Subscription Data
func HTTPGetV2xData(c *gin.Context) {
	logger.SdmLog.Warnln("Handle Get /:supi/v2x-data is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}
