// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudm_SDM

Nudm Subscriber Data Management Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package subscriberdatamanagement

import (
	"github.com/gin-gonic/gin"
	"github.com/omec-project/udm/logger"
)

// Put /:supi/am-data/subscribed-snssais-ack
// Nudm_Sdm Info operation for S-NSSAIs acknowledgement
func HTTPSNSSAIsAck(c *gin.Context) {
	detail := "Handle Put /:supi/am-data/subscribed-snssais-ack is not implemented"
	logger.SdmLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}
