// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudm_SDM

Nudm Subscriber Data Management Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package subscriberdatamanagement

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/openapi/v2/models"
	"github.com/omec-project/udm/logger"
	utilLogger "github.com/omec-project/util/logger"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name string
	// Method is the string for the HTTP method (e.g., GET, POST, etc.)
	Method string
	// Pattern is the pattern of the URI.
	Pattern string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

type routeParamAlias struct {
	canonical string
	original  string
}

// NewRouter returns a new router.
func NewRouter() *gin.Engine {
	router := utilLogger.NewGinWithZap(logger.GinLog)
	AddService(router)
	return router
}

// AddService adds routes to an existing gin engine.
func AddService(engine *gin.Engine) *gin.RouterGroup {
	group := engine.Group("/nudm-sdm/v2")
	for _, route := range getRoutes() {
		if shouldSkipRoute(route.Pattern) {
			continue
		}
		if route.HandlerFunc == nil {
			route.HandlerFunc = DefaultHandleFunc
		}
		ginPattern, aliases := canonicalizeRoutePattern(route.Pattern)
		handlerFunc := wrapRouteHandler(route.HandlerFunc, aliases)
		switch route.Method {
		case http.MethodGet:
			group.GET(ginPattern, handlerFunc)
		case http.MethodOptions:
			group.OPTIONS(ginPattern, handlerFunc)
		case http.MethodPost:
			group.POST(ginPattern, handlerFunc)
		case http.MethodPut:
			group.PUT(ginPattern, handlerFunc)
		case http.MethodPatch:
			group.PATCH(ginPattern, handlerFunc)
		case http.MethodDelete:
			group.DELETE(ginPattern, handlerFunc)
		}
	}

	return group
}

// Default handler for not yet implemented routes
func DefaultHandleFunc(c *gin.Context) {
	writeNotImplementedProblem(c, "This API route is not implemented")
}

func writeNotImplementedProblem(c *gin.Context, detail string) {
	problemDetails := models.NewProblemDetails()
	problemDetails.SetStatus(http.StatusNotImplemented)
	problemDetails.SetCause("NOT_IMPLEMENTED")
	problemDetails.SetDetail(detail)
	c.JSON(http.StatusNotImplemented, problemDetails)
}

func shouldSkipRoute(pattern string) bool {
	return strings.Contains(pattern, "request.body#")
}

func canonicalizeRoutePattern(pattern string) (string, []routeParamAlias) {
	segments := strings.Split(pattern, "/")
	aliases := make([]routeParamAlias, 0)
	for index, segment := range segments {
		if len(segment) <= 1 || segment[0] != ':' {
			continue
		}
		original := segment[1:]
		canonical := fmt.Sprintf("param%d", index)
		segments[index] = ":" + canonical
		if original != canonical {
			aliases = append(aliases, routeParamAlias{canonical: canonical, original: original})
		}
	}
	return strings.Join(segments, "/"), aliases
}

func wrapRouteHandler(handler gin.HandlerFunc, aliases []routeParamAlias) gin.HandlerFunc {
	if len(aliases) == 0 {
		return handler
	}

	return func(c *gin.Context) {
		for _, alias := range aliases {
			value := c.Param(alias.canonical)
			if value == "" {
				continue
			}
			c.Params = append(c.Params, gin.Param{Key: alias.original, Value: value})
		}
		handler(c)
	}
}

func getRoutes() []Route {
	return []Route{
		{
			"GetA2xData",
			http.MethodGet,
			"/:supi/a2x-data",
			HTTPGetA2xData,
		},
		{
			"GetAmData",
			http.MethodGet,
			"/:supi/am-data",
			HTTPGetAmData,
		},
		{
			"GetMbsData",
			http.MethodGet,
			"/:supi/5mbs-data",
			HTTPGetMbsData,
		},
		{
			"GetEcrData",
			http.MethodGet,
			"/:supi/am-data/ecr-data",
			HTTPGetEcrData,
		},
		{
			"GetSupiOrGpsi",
			http.MethodGet,
			"/:ueId/id-translation-result",
			HTTPGetSupiOrGpsi,
		},
		{
			"GetGroupIdentifiers",
			http.MethodGet,
			"/group-data/group-identifiers",
			HTTPGetGroupIdentifiers,
		},
		{
			"GetLcsBcaData",
			http.MethodGet,
			"/:supi/lcs-bca-data",
			HTTPGetLcsBcaData,
		},
		{
			"GetLcsMoData",
			http.MethodGet,
			"/:supi/lcs-mo-data",
			HTTPGetLcsMoData,
		},
		{
			"GetLcsPrivacyData",
			http.MethodGet,
			"/:ueId/lcs-privacy-data",
			HTTPGetLcsPrivacyData,
		},
		{
			"GetLcsSubscriptionData",
			http.MethodGet,
			"/:supi/lcs-subscription-data",
			HTTPGetLcsSubscriptionData,
		},
		{
			"GetMultipleIdentifiers",
			http.MethodGet,
			"/multiple-identifiers",
			HTTPGetMultipleIdentifiers,
		},
		{
			"GetProseData",
			http.MethodGet,
			"/:supi/prose-data",
			HTTPGetProseData,
		},
		{
			"CAGAck",
			http.MethodPut,
			"/:supi/am-data/cag-ack",
			HTTPCAGAck,
		},
		{
			"SNSSAIsAck",
			http.MethodPut,
			"/:supi/am-data/subscribed-snssais-ack",
			HTTPSNSSAIsAck,
		},
		{
			"SorAckInfo",
			http.MethodPut,
			"/:supi/am-data/sor-ack",
			HTTPSorAckInfo,
		},
		{
			"UpuAck",
			http.MethodPut,
			"/:supi/am-data/upu-ack",
			HTTPUpuAck,
		},
		{
			"GetRangingSlPosData",
			http.MethodGet,
			"/:supi/ranging-slpos-data",
			HTTPGetRangingSlPosData,
		},
		{
			"GetDataSets",
			http.MethodGet,
			"/:supi",
			HTTPGetDataSets,
		},
		{
			"GetSharedData",
			http.MethodGet,
			"/shared-data",
			HTTPGetSharedData,
		},
		{
			"GetIndividualSharedData",
			http.MethodGet,
			"/shared-data/:sharedDataId",
			HTTPGetIndividualSharedData,
		},
		{
			"GetSmfSelData",
			http.MethodGet,
			"/:supi/smf-select-data",
			HTTPGetSmfSelData,
		},
		{
			"GetSmsMngtData",
			http.MethodGet,
			"/:supi/sms-mng-data",
			HTTPGetSmsMngtData,
		},
		{
			"GetSmsData",
			http.MethodGet,
			"/:supi/sms-data",
			HTTPGetSmsData,
		},
		{
			"GetSmData",
			http.MethodGet,
			"/:supi/sm-data",
			HTTPGetSmData,
		},
		{
			"GetNSSAI",
			http.MethodGet,
			"/:supi/nssai",
			HTTPGetNSSAI,
		},
		{
			"Subscribe",
			http.MethodPost,
			"/:ueId/sdm-subscriptions",
			HTTPSubscribe,
		},
		{
			"SubscribeToSharedData",
			http.MethodPost,
			"/shared-data-subscriptions",
			HTTPSubscribeToSharedData,
		},
		{
			"Unsubscribe",
			http.MethodDelete,
			"/:ueId/sdm-subscriptions/:subscriptionId",
			HTTPUnsubscribe,
		},
		{
			"UnsubscribeForSharedData",
			http.MethodDelete,
			"/shared-data-subscriptions/:subscriptionId",
			HTTPUnsubscribeForSharedData,
		},
		{
			"Modify",
			http.MethodPatch,
			"/:ueId/sdm-subscriptions/:subscriptionId",
			HTTPModify,
		},
		{
			"ModifySharedDataSubs",
			http.MethodPatch,
			"/shared-data-subscriptions/:subscriptionId",
			HTTPModifySharedDataSubs,
		},
		{
			"GetTimeSyncSubscriptionData",
			http.MethodGet,
			"/:supi/time-sync-data",
			HTTPGetTimeSyncSubscriptionData,
		},
		{
			"GetTraceConfigData",
			http.MethodGet,
			"/:supi/trace-data",
			HTTPGetTraceConfigData,
		},
		{
			"UpdateSORInfo",
			http.MethodPost,
			"/:supi/am-data/update-sor",
			HTTPUpdateSORInfo,
		},
		{
			"GetUeCtxInAmfData",
			http.MethodGet,
			"/:supi/ue-context-in-amf-data",
			HTTPGetUeCtxInAmfData,
		},
		{
			"GetUeCtxInSmfData",
			http.MethodGet,
			"/:supi/ue-context-in-smf-data",
			HTTPGetUeCtxInSmfData,
		},
		{
			"GetUeCtxInSmsfData",
			http.MethodGet,
			"/:supi/ue-context-in-smsf-data",
			HTTPGetUeCtxInSmsfData,
		},
		{
			"GetUcData",
			http.MethodGet,
			"/:supi/uc-data",
			HTTPGetUcData,
		},
		{
			"GetV2xData",
			http.MethodGet,
			"/:supi/v2x-data",
			HTTPGetV2xData,
		},
		{
			"DataRestorationNotificationRequestBodyDataRestorationCallbackUriPost",
			http.MethodPost,
			"/:request.body#/dataRestorationCallbackUri",
			HTTPDataRestorationNotificationRequestBodyDataRestorationCallbackUriPost,
		},
		{
			"DatachangeNotificationUeIdRequestBodyCallbackReferencePost",
			http.MethodPost,
			"/:request.body#/callbackReference",
			HTTPDatachangeNotificationUeIdRequestBodyCallbackReferencePost,
		},
		{
			"DatachangeNotificationRequestBodyCallbackReferencePost",
			http.MethodPost,
			"/:request.body#/callbackReference",
			HTTPDatachangeNotificationRequestBodyCallbackReferencePost,
		},
	}
}
