// Copyright (c) 2026 Intel Corporation
// Copyright 2019 free5GC.org
// SPDX-License-Identifier: Apache-2.0

/*
Nudm_EE

Nudm Event Exposure Service.
© 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.5

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package eventexposure

import (
	"github.com/gin-gonic/gin"
	"github.com/omec-project/udm/logger"
	"github.com/omec-project/udm/producer"
	"github.com/omec-project/util/httpwrapper"
)

// Delete /:ueIdentity/ee-subscriptions/:subscriptionId
// Unsubscribe
func HTTPDeleteEeSubscription(c *gin.Context) {
	logger.EeLog.Infoln("Handle Delete /:ueIdentity/ee-subscriptions/:subscriptionId")
	req := httpwrapper.NewRequest(c.Request, nil)
	req.Params["ueIdentity"] = c.Params.ByName("ueIdentity")
	req.Params["subscriptionID"] = c.Params.ByName("subscriptionId")

	rsp := producer.HandleDeleteEeSubscription(req)
	// only return 204 no content
	c.Status(rsp.Status)
}
