// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudm_EE

Nudm Event Exposure Service.
© 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.5

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package eventexposure

import (
	"github.com/gin-gonic/gin"
	"github.com/omec-project/udm/logger"
)

// Post /:request.body#/callbackReference
func HTTPEventOccurrenceNotificationRequestBodyCallbackReferencePost(c *gin.Context) {
	detail := "Handle Post /:request.body#/callbackReference is not implemented"
	logger.EeLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}
