// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudm_EE

Nudm Event Exposure Service.
© 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.5

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package eventexposure

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/udm/logger"
)

// Post /:request.body#/dataRestorationCallbackUri
func HTTPDataRestorationNotificationRequestBodyDataRestorationCallbackUriPost(c *gin.Context) {
	logger.EeLog.Warnln("Handle Post /:request.body#/dataRestorationCallbackUri is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}
